name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "file:./test.db?connection_limit=1"
      NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
      NEXT_PUBLIC_SITE_NAME: "Lucy Joyce | Software Developer"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run linting
        run: npm run lint || echo "Linting failed but continuing..."

      - name: Run tests
        run: npm test
